languages = ["Python", "C++", "Golang", "Rust"]
operations = ["+", "-", "*", "/", "log", "sqrt"]
generation_methods = ["переменные", "массив"]
type = ["int", "float"]
headers = ['Количество чисел', 'Язык', 'Тип данных','Операция', 'Метод генерации','Время выполнения','Результат', 'Состояние']
